### PR TITLE
Add CHD1D

### PR DESCRIPTION
**Pull request by duongoku**
This change is [Reviewable](https://reviewable.io/reviews/natsukagami/codefun-chd-statements/4)

### CODE REVIEW

**Comment by duongoku** [comment]
Đi ngủ k

**Comment by natsukagami** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHD1E.md, line 28 at r2](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/4#-L1yh3EsDzAKGN8uws4I:-L1yh3EsDzAKGN8uws4J:b-cn5uxk) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/4237ca0edcf9c96e26f23fed9973f459aa5285d9/CHD1E.md#L28)):*
> ```Markdown
> ### Input
> ```
> 1 1 1 1
> ```

Nó là 
```
1
1 1
1
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/4)*

**Comment by natsukagami** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/4)*

**Comment by natsukagami** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/4#-:-L1zQq2vdx5K3r62b0wj:bnfp4nl)*

**Comment by natsukagami** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/4#-:-L1zRQJ3HmJ7Y_gKgicr:bnfp4nl)*

**Pull request merged**
