### PR TITLE
Update

### PR DESCRIPTION
**Pull request by duongoku**
This change is [Reviewable](https://reviewable.io/reviews/natsukagami/codefun-chd-statements/10)

### CODE REVIEW

**Comment by natsukagami** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[CHD2D.md, line 5 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29Yu7IJxtK7-n5qETN:-L29Yu7IJxtK7-n5qETO:b-94zlfx) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2D.md#L5)):*
> lúc còn n chai là no

`n`

---

*[CHD2D.md, line 7 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29YxO80wCFfp2ozxmx:-L29YxO80wCFfp2ozxmy:bl0eciv) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2D.md#L7)):*
>  n 

`n`

---

*[CHD2D.md, line 7 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29Z-94lGjY8xU8z2NH:-L29Z-956C9erThR8KQo:bwb7u00) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2D.md#L7)):*
> …..

để 3 dấu thôi nhỉ 

---

*[CHD2D.md, line 11 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29ZAb_jLbkJisUgB4H:-L29ZAb_jLbkJisUgB4I:bg2zkog) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2D.md#L11)):*
> ….

để 3 dấu thôi nhỉ 

---

*[CHD2D.md, line 21 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29ZEpjp-QLqbSovAq5:-L29ZEpjp-QLqbSovAq6:bphzmvr) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2D.md#L21)):*
> <3000
`< 3000`

---

*[CHD2E.md, line 5 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29ZVEhbJfmAx5c9ca9:-L29ZVEhbJfmAx5c9caA:b-hyu5r8) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2E.md#L5)):*
> n cầu thủ Mờ-U và m cầu thủ Borussia Dortmund

`n` và `m`

---

*[CHD2E.md, line 9 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29ZXb9z8T8ORsYPD-o:-L29ZXbAY8wRpXX_wSqq:bcl2ue8) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2E.md#L9)):*
> ```Markdown
> Mỗi cầu thủ Mờ-U hay Borussia Dortmund sẽ có vị trí trên sân(Thủ Môn, Hậu Vệ, Tiền Vệ, Tiền Đạo,.....), mỗi vị trí sẽ được gọi tắt bằng 1 chữ cái, các cầu thủ cùng vị trí sẽ có cùng chữ cái này. Quy tắc của Poiiiiiii phát biểu như sau:
> 
> Ở một thời điểm, Poiiiiiii sẽ lấy ra cầu thủ có cấp thẻ nhỏ nhất của 1 trong 2 đội và ép, vị trí của cầu thủ này sẽ được lưu lại vào 1 string. Poiiiiiii cho rằng nếu ép xong mà string này là palindrome thì Poiiiiiii sẽ gặp may mắn và ép tiếp Rooney mùa U10 và Van Der Sar E8.
> ```

Thêm `>` thành quote

---

*[CHD2E.md, line 11 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29ZP7Q4JIy3MqHhvT9:-L29ZP7Q4JIy3MqHhvTA:b76qhgh) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2E.md#L11)):*
> aba hay racecar

`aba` hay `racecar`

---

*[CHD2F.md, line 5 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29Zg3NwZy617TUfqIN:-L29Zg3NwZy617TUfqIO:bupmmld) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2F.md#L5)):*
> (`0,0`)

Điểm trong toán được biểu diễn là `(0, 0)` chứ không phải (`0,0`)

---

*[CHD2F.md, line 5 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29Zrzf9fVQsm-RhW29:-L29Zrzf9fVQsm-RhW2A:b76lz64) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2F.md#L5)):*
> (`x[i],y[i]`)

Tương tự 

---

*[CHD2F.md, line 9 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29ZuJJeaQF5De_p9-8:-L29ZuJJeaQF5De_p9-9:b-2urne0) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2F.md#L9)):*
> t[i])

?

---

*[CHD2G.md, line 7 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29_17dPKPsus3YHk2N:-L29_17dPKPsus3YHk2O:bxsi4pu) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2G.md#L7)):*
> (`0,x`)

Tương tự file CHD2F.md, `(0, x)`

---

*[CHD2H.md, line 5 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29_PPBAQ61jJhk0w3L:-L29_PPCZSKcNEbH6i0Z:b-725xlh) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2H.md#L5)):*
> N người

`N` người

---

*[CHD2H.md, line 13 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29_gloikWlwDgeg2Km:-L29_glpM_R3803pep-K:b2qznw9) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2H.md#L13)):*
> với M team

với `M` team

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10)*

**Comment by duongoku** [comment]
Review status: 4 of 9 files reviewed at latest revision, 14 unresolved discussions.

---

*[CHD2D.md, line 5 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29Yu7IJxtK7-n5qETN:-L29x0H_1SJryhyWtsAt:b-896fix) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2D.md#L5)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

> lúc còn n chai là no

`n`
</blockquote></details>

Done.

---

*[CHD2D.md, line 7 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29YxO80wCFfp2ozxmx:-L29x0mKE0a1vyQgMHAI:b-896fix) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2D.md#L7)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

>  n 

`n`
</blockquote></details>

Done.

---

*[CHD2D.md, line 7 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29Z-94lGjY8xU8z2NH:-L29x1FXUEd0hsssAA8T:b-896fix) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2D.md#L7)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

> …..

để 3 dấu thôi nhỉ 
</blockquote></details>

Done.

---

*[CHD2D.md, line 11 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29ZAb_jLbkJisUgB4H:-L29x1j_WtIw90GfL6Dn:b-896fix) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2D.md#L11)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

> ….

để 3 dấu thôi nhỉ 
</blockquote></details>

Done.

---

*[CHD2D.md, line 21 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29ZEpjp-QLqbSovAq5:-L29x2CyDJHdp_XhFvDO:b-896fix) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2D.md#L21)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

> <3000
`< 3000`
</blockquote></details>

Done.

---

*[CHD2E.md, line 5 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29ZVEhbJfmAx5c9ca9:-L29x2iKaA5fiO5PftLH:b-896fix) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2E.md#L5)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

> n cầu thủ Mờ-U và m cầu thủ Borussia Dortmund

`n` và `m`
</blockquote></details>

Done.

---

*[CHD2E.md, line 9 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29ZXb9z8T8ORsYPD-o:-L29x3ASKrlGXKHOlmSw:b-896fix) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2E.md#L9)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

Thêm `>` thành quote
</blockquote></details>

Done.

---

*[CHD2E.md, line 11 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29ZP7Q4JIy3MqHhvT9:-L29x3ciLTVhlum486gy:b-896fix) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2E.md#L11)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

> aba hay racecar

`aba` hay `racecar`
</blockquote></details>

Done.

---

*[CHD2F.md, line 5 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29Zg3NwZy617TUfqIN:-L29x44Tp7m4iWH02lTN:b-896fix) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2F.md#L5)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

> (`0,0`)

Điểm trong toán được biểu diễn là `(0, 0)` chứ không phải (`0,0`)
</blockquote></details>

Done.

---

*[CHD2F.md, line 5 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29Zrzf9fVQsm-RhW29:-L29x4Wx4vEKTrop-KxZ:b-896fix) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2F.md#L5)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

> (`x[i],y[i]`)

Tương tự 
</blockquote></details>

Done.

---

*[CHD2F.md, line 9 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29ZuJJeaQF5De_p9-8:-L29x4zj13WylyUhhYBk:b-896fix) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2F.md#L9)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

> t[i])

?
</blockquote></details>

Done.

---

*[CHD2G.md, line 7 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29_17dPKPsus3YHk2N:-L29x5WUGWAVyJWAJ3A0:b-896fix) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2G.md#L7)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

> (`0,x`)

Tương tự file CHD2F.md, `(0, x)`
</blockquote></details>

Done.

---

*[CHD2H.md, line 5 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29_PPBAQ61jJhk0w3L:-L29wyk4bMNg4xiIJF39:b-896fix) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2H.md#L5)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

> N người

`N` người
</blockquote></details>

Done.

---

*[CHD2H.md, line 13 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29_gloikWlwDgeg2Km:-L29x-PX_wgW1muM2yAV:b-896fix) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2H.md#L13)):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

> với M team

với `M` team
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10)*

**Comment by natsukagami** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[CHD2E.md, line 7 at r2](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29xdC4cdYqTHK5Btwd:-L29xdC4cdYqTHK5Btwe:b-ra3hy7) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/99d005790ab8f743d374999a46fb0c4979563f48/CHD2E.md#L7)):*
> ```Markdown
> Trong FIFAONLINE 3 để tăng sức mạnh một cầu thủ các huấn luyện viên phải nâng cấp bằng cách mua 2 thẻ của một cầu thủ và kết hợp lại(gọi là ép thẻ). Nhưng việc ép này có một khả năng hỏng, hỏng xong thì huấn luyện viên mất cả 2 cầu thủ. Poiiiiiii ép thẻ theo một quy tắc mà Poiiiiiii cho là đem lại may mắn. Poiiiiiii có `n` cầu thủ Mờ-U và `m` cầu thủ Borussia Dortmund, được sắp xếp theo cấp thẻ tăng dần.
> 
> > Mỗi cầu thủ Mờ-U hay Borussia Dortmund sẽ có vị trí trên sân(Thủ Môn, Hậu Vệ, Tiền Vệ, Tiền Đạo,.....), mỗi vị trí sẽ được gọi tắt bằng 1 chữ cái, các cầu thủ cùng vị trí sẽ có cùng chữ cái này. Quy tắc của Poiiiiiii phát biểu như sau:
> ```

bỏ > ở đây đi

---

*[CHD2F.md, line 5 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29Zg3NwZy617TUfqIN:-L29xl2ZIntGk5sCbFWd:b-3ohu8w) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2F.md#L5)):*
<details><summary><i>Previously, duongoku (duongoku) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

đặt cả ngoặc vào trong `code` ý em

---

*[CHD2F.md, line 9 at r2](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29xq1tHgDB4ZhqhRWT:-L29xq1tHgDB4ZhqhRWU:b-tc5oe8) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/99d005790ab8f743d374999a46fb0c4979563f48/CHD2F.md#L9)):*
>`  , `
thừa dấu cách

---

*[CHD2G.md, line 7 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29_17dPKPsus3YHk2N:-L29xvIAx2FtlDPsFNXm:b-xvt5sf) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2G.md#L7)):*
<details><summary><i>Previously, duongoku (duongoku) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

như trên

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10)*

**Comment by natsukagami** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[CHD2F.md, line 5 at r1](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-L29Zrzf9fVQsm-RhW29:-L29y1Z2zJ0fye_dzKOD:b-xvt5sf) ([raw file](https://github.com/natsukagami/codefun-chd-statements/blob/11468c99d7de401049dbb5f5cde6a60319457dd0/CHD2F.md#L5)):*
<details><summary><i>Previously, duongoku (duongoku) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

như trên

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10)*

**Comment by natsukagami** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/codefun-chd-statements/10#-:-L2FxpExuxS1f8Oubm7v:bnfp4nl)*

**Pull request merged**
